# Generated by Django 4.0.3 on 2022-12-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='href',
        ),
    ]
