# Generated by Django 4.0.3 on 2022-12-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_remove_binvo_href'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoe',
            new_name='Shoes',
        ),
    ]
