# Generated by Django 4.0.3 on 2022-12-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_rename_shoe_shoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='picture_url',
            new_name='pictured_url',
        ),
    ]
