# Generated by Django 4.0.3 on 2022-12-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0005_binvo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
