# Generated by Django 4.0.3 on 2022-12-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0006_alter_binvo_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='import_href',
        ),
    ]
