# Generated by Django 4.0.3 on 2022-12-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0011_rename_pictured_url_shoes_picture_alter_shoes_bin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='picture',
            new_name='pictured_url',
        ),
    ]
